# Generated by Django 4.2.20 on 2025-05-06 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture_main', '0002_article_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog_images/', verbose_name='Изображение'),
        ),
    ]
